export const MODIFY_LIST = "MODIFY_LIST";
export const MODIFY_FORM = "MODIFY_FORM";
export const MODIFY_USER_IS_SCHEDULED_LIST = "MODIFY_USER_IS_SCHEDULED_LIST";
export const UPDATE_SEARCH_TITLE = "UPDATE_SEARCH_TITLE";
export const ADD_RECENT_SEARCH_TERM = "ADD_RECENT_SEARCH_TERM";
