export const UPDATE_SEARCH_TITLE = "UPDATE_SEARCH_TITLE";
export const ADD_RECENT_SEARCH_TERM = "ADD_RECENT_SEARCH_TERM";
export const SET_PARAMS = "SET_PARAMS";
export const CLEAR_PARAMS = "CLEAR_PARAMS";
